In [1]:
import torch
import math

In [2]:
dtype = torch.float
device = torch.device("cpu")

print("dtype: ", dtype)
print("device: ", device)

dtype:  torch.float32
device:  cpu


In [3]:
# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

In [4]:
# Randomly initialize weights
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

In [5]:
learning_rate = 1e-6

In [6]:
for t in range(2000):
    # forward pass: compute predicted y
    y_pred = a + b * x + c * x ** 2 + d*x**3
    
    # Compute and print loss
    print(y_pred)

tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,  ..., 32.4427, 32.5337, 32.6250])
tensor([-1.9693, -1.9322, -1.8952,

In [7]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2, 2)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1:')
print(r3) # repeats values of r1 because of re-seed

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [8]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2 # every element is multiplied by 2
print(twos)

threes = ones + twos       # addition allowed because shapes are similar
print(threes)              # tensors are added element-wise
print(threes.shape)        # this has the same dimensions as input tensors

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)
# uncomment this line to get a runtime error
# r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])
